services:
  backend:
    image: emfall/frenchcab-backend:latest
    build: ./backend
    container_name: conteneur-back
    ports:
      - "3001:3001"
    volumes:
     - ./backend:/app
     - /app/node_modules
     - ./backend/data:/app/data 
    restart: always

  frontend:
    image: emfall/frenchcab-frontend:latest
    build: ./frontend
    container_name: conteneur-front
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - gateway
    restart: always


  gateway:
    image: emfall/frenchcab-gateway:latest
    build: ./gateway
    container_name: conteneur-gateway
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always