services:
  backend:
    build: ./backend
    container_name: conteneur-back

  frontend:
    build: ./frontend
    container_name: conteneur-front
  
  gateway:
    build: ./gateway
    container_name: contenur-gateway
