name: Frenchcab - CD - Déploiement

run-name: ${{ github.actor }} - CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Se connecter à la VM Azure
      - name: Déployer sur la VM Azure
        uses: appleboy/ssh-action@v1
        with:

          # IP publique de la VM
          host: ${{ vars.VM_HOST }}

          # Utilisateur SSH
          username: ${{ vars.VM_USER }}

          # Mot de passe SSH
          password: ${{ secrets.VM_PASSWORD }}

          # Commandes exécutées sur la VM
          script: |

            # Aller dans le dossier du projet
            cd /home/groupe1/frenchcab

            # Télécharger les nouvelles images depuis Docker Hub
            docker compose pull

            # Redémarrer les conteneurs avec les nouvelles images
            docker compose up -d

            # Attendre et valider le backend
            echo "Waiting for backend"
            for i in $(seq 1 30);do
              if curl -f http://conteneur-back:3001/hello;then
                echo "backend opérationnel après $i secondes."
                break
              fi
              sleep 1
            done

            # En cas d'échec de la boucle
            if [ $? -ne 0 ]; then
              echo "Échec de la connexion au backend après 30 secondes. Arrêt du déploiement."
              exit 1
            fi

            # Vérifier le frontend
            curl --fail http://conteneur-front:80/

            # Vérifier l'état des conteneurs
            echo "Déploiement réussi : services opérationnels."
            docker compose ps