name: Frenchcab - CI - Build et Push Docker

run-name: ${{ github.actor }} - CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Récupérer le code
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      # 2. Créer le fichier .env du backend
      - name: 2. Créer le fichier .env
        run: |
          echo "PORT=3001" > backend/.env

      # 3. Se connecter à Docker Hub
      - name: 3. Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Construire l'image backend
      - name: 4. Construire le backend
        run: |
          docker build \
            -t emfall/frenchcab-backend:latest \
            ./backend

      # 5. Construire l'image frontend
      - name: 5. Construire le frontend
        run: |
          docker build \
            -t emfall/frenchcab-frontend:latest \
            ./frontend

      # 6. Lancer les conteneurs pour tester
      - name: 6. Lancer les conteneurs
        run: docker compose up -d

      # 7. Vérifier l'état des conteneurs
      - name: 7. Vérifier les conteneurs
        run: docker compose ps

      # 8. Attendre que le backend réponde
      - name: 8. Tester le backend
        run: |
          for i in $(seq 1 30); do
            if curl -f https://conteneur-back:3001/hello/ ; then
              echo "Backend disponible !"
              exit 0
            fi

            sleep 1
          done

          echo "Le backend ne répond pas"
          docker compose logs backend
          exit 1

      # 9. Tester l'API
      - name: 9. Tester les endpoints
        run: |
          curl --fail https://conteneur-back:3001/hello/
         

      # 10. Tester le frontend
      - name: 10. Tester le frontend
        run: |
          curl --fail https://conteneur-front:4200/

      # 11. Afficher les logs en cas de problème
      - name: 11. Afficher les logs
        if: always()
        run: docker compose logs

      # 12. Arrêter les conteneurs
      - name: 12. Arrêter les conteneurs
        if: always()
        run: docker compose down

      # 13. Envoyer le backend sur Docker Hub
      - name: 13. Push backend
        if: success()
        run: |
          docker push emfall/frenchcab-backend:latest

      # 14. Envoyer le frontend sur Docker Hub
      - name: 14. Push frontend
        if: success()
        run: |
          docker push emfall/frenchcab-frontend:latest