name: Frenchcab - CI - Build et Push Docker

run-name: ${{ github.actor }} - CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Récupérer le code
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      # 2. Créer le fichier .env du backend
      - name: 2. Créer le fichier .env
        run: |
          echo "PORT=3001" > backend/.env

      # 3. Se connecter à Docker Hub
      - name: 3. Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Construire l'image du gateway
      - name: 4. Construire le gateway
        run: |
          docker build\
           -t emfall/frenchcab-gateway:latest \
          ./gateway

      # 5. Construire l'image backend
      - name: 5. Construire le backend
        run: |
          docker build \
            -t emfall/frenchcab-backend:latest \
            ./backend

      # 6. Construire l'image frontend
      - name: 6. Construire le frontend
        run: |
          docker build \
            -t emfall/frenchcab-frontend:latest \
            ./frontend

      # 7. Lancer les conteneurs pour tester
      - name: 7. Lancer les conteneurs
        run: docker compose up -d

      # 8. Vérifier l'état des conteneurs
      - name: 8. Vérifier les conteneurs
        run: docker compose ps

      # 9. Attendre que le backend réponde
      # - name: 9. Tester le backend
      #   run: |
      #     for i in $(seq 1 30); do
      #       if curl -f http://localhost:3001/hello ; then
      #         echo "Backend disponible !"
      #         exit 0
      #       fi

      #       sleep 1
      #     done

      #     echo "Le backend ne répond pas"
      #     docker compose logs backend
      #     exit 1

      # 10. Tester l'API
      - name: 10. Tester les endpoints
        run: |
          curl --fail http://localhost:3001/hello/
         

      # 11. Tester le frontend 
      - name: 11. Tester le frontend
        run: |
          for i in $(seq 1 30); do
            if curl --fail http://localhost:4200/ ; then
              echo "Frontend disponible !"
              exit 0
            fi

            echo "Attente du frontend..."
            sleep 1
          done

          echo "Le frontend ne répond pas"
          docker compose logs frontend
          exit 1

      # 12. Afficher les logs en cas de problème
      - name: 12. Afficher les logs
        if: always()
        run: docker compose logs

      # 13. Arrêter les conteneurs
      - name: 13. Arrêter les conteneurs
        if: always()
        run: docker compose down

      # 14. Envoyer le gateway sur Docker Hub
      - name: 14. Push gateway
        if: success()
        run: |
          docker push emfall/frenchcab-gateway:latest

      # 15. Envoyer le backend sur Docker Hub
      - name: 15. Push backend
        if: success()
        run: |
          docker push emfall/frenchcab-backend:latest

      # 16. Envoyer le frontend sur Docker Hub
      - name: 16. Push frontend
        if: success()
        run: |
          docker push emfall/frenchcab-frontend:latest